### ISSUE TITLE
ActionScript  : Remove backgrounds from Images

### ISSUE THREAD

**Issue by Tclack88** [Lambda-School-Labs/trashpanda-ds#7]
Actionscript for automating background removal in photoshop

**Comment by tobias-fyi** [comment]
The feature I used to do this is called Photoshop Actions - no scripting involved (unfortunately). But it works great!

I can remove the background from an image about every 2 seconds. If that performance holds, I can crunch a batch of 1,000 images about every half hour.

I'm going to mark this issue as closed, and open a new one for when I start crunching our actual dataset.
